### ISSUE TITLE
Разные форматы ответа для публикации черновиков

### ISSUE THREAD

**Issue by ghost** [JekaGrib/lola#10]
почему [ok1](https://github.com/JekaGrib/lola/blob/migrations/scripts/publishDraft/ok1) выдает
```json
{"status":"created","post_id":104}
```
а [ok2](https://github.com/JekaGrib/lola/blob/migrations/scripts/publishDraft/ok2) выдает

```json
{"post_id":34,"author":{"author_id":50,"author_info":"Vestibulum sed magna at nunc commodo placerat.","user_id":50},"post_name":"suspendisse ornare consequat","post_create_date":"2019-04-07","post_category":{"category_id":129,"sub_categories":[176],"category_name":"curae","super_category":{"category_id":77,"sub_categories":[117,129,140],"category_name":"ut","super_category":{"category_id":56,"sub_categories":[77,92],"category_name":"augue","super_category":{"category_id":18,"sub_categories":[41,56],"category_name":"bibendum"}}}},"post_text":"vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse","post_main_pic_id":451,"post_main_pic_url":"http://localhost:3000/pictures/451","post_pics":[{"pic_id":142,"pic_url":"http://localhost:3000/pictures/142"},{"pic_id":271,"pic_url":"http://localhost:3000/pictures/271"},{"pic_id":116,"pic_url":"http://localhost:3000/pictures/116"},{"pic_id":320,"pic_url":"http://localhost:3000/pictures/320"}],"post_tags":[{"tag_id":66,"tag_name":"nisl"},{"tag_id":92,"tag_name":"libero"}]}
```

**Comment by JekaGrib** [comment]
Черновик может создаваться с нуля (пост_ид = нул) или на основании поста (содержит все данные поста, юзер их меняет, затем публикует и пост, на основе которого создан черновик, меняется). Когда черновик публикуется, если его пост_ид пустой, то создается новый пост (ответ на ок1, метод POST), если это черновик поста(пост_ид равен числу), то пост не создается, меняется старый (ответ на ок2, метод PUT)

**Comment by ghost** [comment]
Действительно, он создает пост, при том при каждой публикации создается новый пост. Разве повторные вызовы данного скрипта не должны редактировать пост, который был создан после первого вызова, если нет тогда каким образом проихсодит редактирование постов созданных из этого черновика? Вообще не совсем ясно зачем из одного черновика можно создать кучу постов.

**Comment by JekaGrib** [comment]
Редактирование поста происходит созданием его черновика и опубликованием. Вообще я планировала удалять черновик сразу после его публикации. Но увидела коммент Сергея, что можно не удалять и оставила https://rizzoma.com/topic/c27faf1cfa188c1120f59af4c35e6099/0_b_9n8n_8p53a/. Могу добавить удаление, т.к. его хранение, действительно, не имеет никакого смысла и получается, что "из одного черновика можно создать кучу постов."

**Comment by ghost** [comment]
Там речь шла о черновиках, которые обновляют новость ("При вызове метода "publish" у черновика его содержимое заменяет содержимое новости"). У тебя же этот черновик после публикации уже не делает ничего полезного, поэтому его следует удалять вместе с публикацией поста. Хотя проще было бы просто менять null на айди созданного поста и использовать его для редактирования.

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/lola/issues/10 https://github.com/JekaGrib/lola/commit/a210567711bb2c00b6e921a371c882b3be44e118
