### ISSUE TITLE
Повторяющийся код

### ISSUE THREAD

**Issue by ghost** [JekaGrib/lola#11]
тут очень много повторений одного и того же кода
https://github.com/JekaGrib/lola/blob/a210567711bb2c00b6e921a371c882b3be44e118/src/Conf.hs#L85-L189

**Comment by JekaGrib** [comment]
#11 https://github.com/JekaGrib/lola/pull/9/commits/832ec6ebb2fad41e3bcd0e9c11612727ced422bf
