### ISSUE TITLE
Расширения

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/lola#5]
Привет!
Некоторые часто используемые расширения, как например `RecordWildCards`, `OverloadedStrings`, можно вынести в `package.yaml`, нет смысла их дублировать в каждом файле
То же касается и предупреждений компилятора `-Wall -Werror`

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/lola/issues/5 https://github.com/JekaGrib/lola/commit/f4c1d10e17db7e396172a9a5460a3dc78a27e074
