### ISSUE TITLE
Наименования полей

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/lola#6]
Можешь объяснить, что это за странные наименования с цифрами?
```
data DraftsResponse = DraftsResponse
  { page9 :: Page,
    drafts9 :: [DraftResponse]
  }
  deriving (Eq, Show)
```

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/lola/issues/6 https://github.com/JekaGrib/lola/commit/17b03f038b27e71f71658155576a13f34aced5d8
