### ISSUE TITLE
Проверка орфографии

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/lola#7]
Если ты пользуешься VSCode, то можно установить расширение для проверки орфографии code spell checker. Я правда нашел только одну ошибку, зато по всему коду `Resourse`
Имена переменных должны содержать английские слова в `camelCase` или общепринятые сокращения. В основном у тебя это соблюдается, кроме некоторых `getTxtstart`, `maybTag`, `leng`

**Comment by JekaGrib** [comment]
А как code spell checker должен ругаться на Resourse? 
![Снимок экрана от 2022-06-15 16-28-45](https://user-images.githubusercontent.com/63345092/173839381-3d3ca530-4311-44da-8816-cce686de7a02.png)
Вроде не ругается

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/lola/issues/7 https://github.com/JekaGrib/lola/commit/0747013aaa54d9289e1a8eacf2e09f670cc71729

**Comment by roman-bodavskiy** [comment]
У меня сейчас почемуто тоже не работает. Но влюбом случае, это ошибка и надо исправить
![Screenshot from 2022-06-29 14-30-04](https://user-images.githubusercontent.com/92144831/176427098-5a24dbff-1b79-42f5-a878-d7c4ab0578f0.png)

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/lola/pull/9/commits/4f30eb7111455a4a9e2149bb00d3d92a4e886dbc
